permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: kcd.github.com
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: kcd
archive: Son Girdiler
assets: /assets
author: Kamile Canan Demirel
disqus: kcd
email: kcd@bil.omu.edu.tr
facebook: https://facebook.com/cnndmrl
feed: ~
flickr: ~
google: ~
googleanalyticsid: ~
googleplus: ~
gpg: ~
homeurl: http://kcd.github.com
logo: /assets/19/19-normal-128x128.png
organization: 19
picasa: ~
related: Diğer Girdiler
repository: kcd.github.com
ribbon: GitHub'dayım
title: kcd
twitter: ~

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar
        9: Kısa Notlar
